### ISSUE TITLE
Highlight problem with self-closing tag

### ISSUE THREAD

**Issue by Cedricbob** [natewallace/angular2-inline#10]
With self-closing:
![broken](https://cloud.githubusercontent.com/assets/7500369/22186586/caa0c6d0-e0c5-11e6-876d-da926cd5fed1.JPG)

Without:
![ok](https://cloud.githubusercontent.com/assets/7500369/22186587/caa19308-e0c5-11e6-896f-8e3fe3b88457.JPG)

**Comment by natewallace** [comment]
My understanding is that the input element is a void element and as such it is not valid html for it to have a closing or self closing tag.  It would be valid in xhtml but I'm assuming that isn't what you are generating here.

**Comment by Cedricbob** [comment]
Yes, you're right. I was confused because most IDE and browser ignore them but this is an invalid syntax. https://www.w3.org/TR/html5/syntax.html#void-elements
