### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by davidalee** [natewallace/angular2-inline#11]
with a `(click)="export()"`:
![screen shot 2017-01-29 at 11 30 22 am](https://cloud.githubusercontent.com/assets/8321301/22405828/6e2f4132-e616-11e6-8ba2-7710cd54fd08.png)

without `(click)=export()"`:
![screen shot 2017-01-29 at 11 30 29 am](https://cloud.githubusercontent.com/assets/8321301/22405829/6fbe588a-e616-11e6-8581-57d57322f731.png)

fwiw I also tried removing all of the html preceding this button but experienced the same highlighting issue.

**Comment by natewallace** [comment]
The problem here is that the text that appears as the attribute value for bound attributes is being highlighted using typescript rules.  If you add a semi-colon( ; ) after the export() statement it should fix highlighting.

I will look at making it possible to exclude the semi-colon.

**Comment by natewallace** [comment]
Actually, on further review it appears that the problem may be that you are using the name 'export' for a method name which is a keyword in typescript.  Adding a semi-colon to the end of the statement will fix the highlighting but you may want to rename your method so it doesn't use the export keyword.  

Highlighting should work without an ending semi-colon provided they aren't named with a keyword.

**Comment by davidalee** [comment]
You're right, that resolved it.

Thanks for creating such a useful extension!
