### ISSUE TITLE
Code completion not working on v 1.9?

### ISSUE THREAD

**Issue by fleps** [natewallace/angular2-inline#13]
Hi there!

I just installed this extension but for me it's not working properly.

The code is correctly highlighted inside ` `` ` but the code completion for html tags isn't working, it only shows normal JS completions.

![image](https://cloud.githubusercontent.com/assets/20216453/22751273/f5895198-ee1a-11e6-9cd4-09a87417e5fe.png)

I tried disabling all my other extensions but didn't worked out. Or disabling will not work if there is a conflict, it has to be uninstalled? 

Thanks!

**Comment by natewallace** [comment]
The code completion only works with tag names.  For example if you type a '<' character the code completion feature will list standard html tags.  If you are typing outside of a tag name the default js completions are displayed.  

This is consistent with how completions are done in the rest of a js file.  For example you will still get default code completion prompts when you are typing inside of a string or a comment.
