### ISSUE TITLE
False error

### ISSUE THREAD

**Issue by thbt** [natewallace/angular2-inline#14]
Thanks a lot for your plugin, it's really useful ! 

I have a small issue : it seems to pick up a false orphan chevron. Don't know if it's related to your plugin, but my template seems fine.

![capture](https://cloud.githubusercontent.com/assets/7943281/23074386/dd655baa-f538-11e6-9f11-287727fbabbc.JPG)

**Comment by natewallace** [comment]
The syntax highlighter for the typescript that appears as the value for the [style.cursor] attribute is expecting a complete expression.  If you surround your ternary expression with parens it should fix the highlighting:

```javascript
(readonly ? 'default' : 'pointer')
```
