### ISSUE TITLE
False Positive Error when using template selector of component from another module

### ISSUE THREAD

**Issue by pain0486** [natewallace/angular2-inline#24]
I have several issues like this scattered throughout my project but here is one example.
I have an AttendanceCardComponent
`@Component({
   selector: 'tx-attendance-card',
   templateUrl: 'attendance-card.component.html',
   providers: [AttendanceService]
})
export class AttendanceCardComponent implements OnInit {
   @Input() public log: AttendanceLog;
   @Input() public userId: string;
   constructor(private alerts: AlertService, private route: ActivatedRoute) {}
   public ngOnInit(): void {
      this.route.paramMap.subscribe(s =>
         this.userId = this.userId || s.get('id')
      , err => this.alerts.addDanger('Something went wrong while accessing the route params'));
   }
}`
and it is declared and exported in an attendance module
`
@NgModule({
   imports: [
      SharedModule,
      AttendanceRoutingModule
   ],
   declarations: [
      AttendanceReportComponent,
      AttendanceCardComponent,
      AttendanceIndvReportComponent,
      AttendanceModalComponent
   ],
   exports: [
      AttendanceReportComponent,
      AttendanceCardComponent,
      AttendanceIndvReportComponent,
      AttendanceModalComponent
   ],
   providers: [AttendanceService, AttendanceReportResolver, AttendanceIndvReportResolver]
})
export class AttendanceModule { }`

Then I have an ProfileModule which imports the AttendanceModule
`@NgModule({
   imports: [
      ProfileRoutingModule,
      AttendanceModule,
      ConsentsModule,
      DynamicFormsModule,
      JournalsModule,
      ProgramProgressModule,
      SharedModule,
      TreatmentPlanModule,
   ],
   declarations: [
      ProfileComponent,
      ProfileInfoComponent
   ],
   providers: [ProfileResolver, ProfileService, MyStoryService]
})
export class ProfileModule { }`

In the ProfileComponent template shown below. I incorporate the attendanceCardComponent by selector and receive the error pictured. However it is part of a module and it compiles and runs fine.
![image](https://user-images.githubusercontent.com/11378706/27349573-5f78f0a4-55bd-11e7-8734-a476c4aecfff.png)

**Comment by natewallace** [comment]
The angular2-inline plugin is used to provide syntax highlighting to template strings assigned to the Component.Template property.  Your example does not appear to have any code that this plugin would highlight.  The intellisense error you are getting appears to be originating from vscode's built-in support for angular.  You will need to log this issue with the vscode team.

**Comment by pain0486** [comment]
@natewallace OK...
Does it make a difference if disabling the angular2-inline plugin gets rid of the errors? 
That is why I started here. Because disabling the plugin makes the warnings go away.

**Comment by natewallace** [comment]
That is strange since this plugin should only effect highlighting in .js and .ts files.  Are you sure it is the angular2-inline plugin you have installed and not some other angular plugin.

**Comment by pain0486** [comment]
I have Angular Essentials installed so it could be one of those. Angular Language Service is one of those.
Apparently this is something that occurs when having both Angular Language Service and this plugin enabled causes. Disabling either one seems to do the trick.

also shows the error on inline components?
![image](https://user-images.githubusercontent.com/11378706/27352182-6a704978-55c5-11e7-991f-30a8408a860b.png)

**Comment by pain0486** [comment]
@natewallace you can close this its apparently an issue with the Angular Language Service only. Thanks
