### ISSUE TITLE
Mark inline html as language html

### ISSUE THREAD

**Issue by mjbvz** [natewallace/angular2-inline#28]
**Problem**
Template strings are currently marked as `language: javascript / typescript`

<img width="749" alt="screen shot 2017-09-18 at 5 46 44 pm" src="https://user-images.githubusercontent.com/12821956/30570990-95796012-9c99-11e7-8f48-a2d0544dbf68.png">

It should be `html` instead. The language mode effects editor features such as bracket matching and commenting.

**Fix**
VSCode has an `embeddedLanguages` setting that marks language mode.  We just added support for using `embeddedLanguages` with an injected grammar: https://github.com/Microsoft/vscode/issues/34316

I'll submit a PR that does this for this extension

**Comment by natewallace** [comment]
Thanks for the PR.  I'll try and get this merged and deployed tonight.
