### ISSUE TITLE
Highlights breaks on ngFor using variable name "module"

### ISSUE THREAD

**Issue by aclementev** [natewallace/angular2-inline#38]
Hi,

I realized that syntax highlighting breaks when using the variable name "module" in an ngFor and using it in an interpolation binding. 
This is an example when using it (every other extension disabled), working fine:
![working](https://user-images.githubusercontent.com/17129652/42461518-ead3453e-83a0-11e8-8274-13ccc1c2e4f0.PNG)

And the same file, nothing changed but the variable name:
![not-working](https://user-images.githubusercontent.com/17129652/42461495-e262201e-83a0-11e8-82e8-a6c08480e07b.PNG)

Thanks!

**Comment by natewallace** [comment]
This plugin uses a copy of the typescript syntax definition when highlighting sections of the template that are considered code.  In typescript, 'module' is a keyword which is why the highlighting breaks.

**Comment by aclementev** [comment]
I see. I was following the Angular Router tutorial, and they chose an unfortunate variable name then.
Thank you!
