### ISSUE TITLE
code completion of typed object

### ISSUE THREAD

**Issue by mattiLeBlanc** [natewallace/angular2-inline#39]
Hi,
I noticed that if I want to use intellisense it is not working inside the template. 
See my GIF.
Is this by design? 

![inline](https://user-images.githubusercontent.com/5285035/43576217-2784692e-968c-11e8-8a7c-9f4c946b109d.gif)

Besides that really enjoy using your plugin!

**Comment by natewallace** [comment]
This plugin only provides intellisense for html tags.  Javascript intellisense is not supported.

**Comment by mattiLeBlanc** [comment]
Fair enough

**Comment by mattiLeBlanc** [comment]
Do you think it is hard to add that feature? Or is that a different level of complexity?

**Comment by natewallace** [comment]
I suspect it would be a lot of work to try and duplicate the code completion vscode does and I'm not really doing any active development on this plugin anymore.
