### ISSUE TITLE
Is there a reason why this extension wouldn't work with Angular1?

### ISSUE THREAD

**Issue by jvandyke** [natewallace/angular2-inline#5]
I work on an Angular 1.5 project where we use the component syntax. After installing this plugin and restarting, I can't get the highlighting to work.

Here's what it looks like for me:

![](https://cl.ly/2G3Q1W351g1H/Image%202016-12-15%20at%2011.30.15%20AM.png)

I looked through your code, but I don't see anything that's expecting `@Component` or anything Angular2 specific. Maybe I missed something, but it seems that the plugin is only looking for `template\s*:\s*\``.

Am I missing something? Do you know if there's anything preventing this plugin from working with ng1?

**Comment by natewallace** [comment]
I think the problem may be that you still have the language-vscode-javascript-angular2 plugin installed.  The angular2-inline replaces this plugin.  Try uninstalling language-vscode-javascript-angular2 and see if that works.

**Comment by jvandyke** [comment]
You're right! I didn't even know I had that one installed. Thanks!
