### ISSUE TITLE
Doesn't work with latest version of VS Code

### ISSUE THREAD

**Issue by ClaytonBrawley** [natewallace/angular2-inline#9]
I saw someone say they were having the same problem on the marketplace, but never submitted an issue as you suggested. This has always worked for me, and I love it, but it has not been working since I downloaded the latest version.

**Comment by natewallace** [comment]
Can you provide an example of what isn't working?
What version of VSCode do you have?
What other extensions do you have?

**Comment by ClaytonBrawley** [comment]
I figured it out -- very simple fix. I had both the new version of the extension and the old version. This never caused a problem before but I guess it was a new problem when I downloaded the latest version. I am currently using version 1.8.1.  I just got rid of the older version and it's fine. Thanks.
